.\" Manpage for humanfreq.
.TH man 1 "24 Aug 2019" "1.1.3 "humanfreq man page"
.SH NAME
humanfreq \- Show the current CPU frequency in MHz or GHz 
.SH SYNOPSIS
humanfreq [-g] [-v]
.SH DESCRIPTION
humanfreq converts the KHz value in scaling_cur_freq to a more human-digestible format.
.SH OPTIONS
-v 
    Show the version number and exit

-g 
    Show the current CPU frequency in GHz
.SH AUTHOR
Daniel Gurney (dgurney99@gmail.com)
